version: '2.4'

services:
  identidock:
    build: .
    ports:
      - "5000:5000"
    environment:
      ENV: DEV
    volumes:
      - ./app:/app

  dnmonster:
    image: amouat/dnmonster:1.1
    ports:
      - "8080:8080"

  redis:
    image: redis:7.4.2